### ISSUE TITLE
Prompt for git passphrase

### ISSUE THREAD

**Issue by dwrz** [grafov/go-playground#11]
This is probably an issue with my environment rather than a bug with `go-playground`, but I was wondering if you had any insights on this:

```
-*- mode: compilation; default-directory: "~/.go/src/playground/at-2019-06-13-150529/" -*-
Compilation started at Thu Jun 13 15:15:09

go run *.go
Enter passphrase for key '/home/user/.ssh/github': 
```
In the snippet, I'm importing a package that's not in the standard library.

If I run the snippet in a shell with `go run` the snippet compiles and runs correctly. There's no request for the github key.

I'm on `go1.12.5 linux/amd64` `and GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-12`.

By the way -- thanks for making this -- I use it almost every day.

**Comment by grafov** [comment]
It seems the problem is out of the scope of the `go-playground`.

Try `go get` your package inside the Emacs or try `magit` with your github repo? Will it ask the key? For using the ssh keys inside the Emacs I use https://github.com/tarsius/keychain-environment, it solves the issues with key prompting for me.

Look also the answers https://emacs.stackexchange.com/questions/30874/magit-how-to-use-ssh-key-rather-than-being-prompted-for-password

And thank you for the warm words about the project :)

**Comment by dwrz** [comment]
Thank you for those insights -- and for your time! I was able to get everything working again.
